language: cpp
compiler:
  - gcc
  - clang
os:
  - osx
  - linux
osx_image: xcode9.2
matrix:
  exclude:
    - os: osx
      compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
      - python-pip
      - python-numpy
      - python-scipy
      - python-matplotlib
      - python-tornado
install:  
  - "[ ${TRAVIS_OS_NAME} = 'linux' && ${CXX} = g++ ] && export CXX=g++-6 || true"
  - "[ ${TRAVIS_OS_NAME} = 'linux' && ${CXX} = clang++ ] && export CXX=clang++-3.8 || true"
  - "[ ${TRAVIS_OS_NAME} = 'osx' ] && pip install --user scikit-build matplotlib || true"
script:
  - pip install --user scikit-build
  - python setup.py install --user
  - cd test/python && GLOG_v=100 ./forest.py && cd ../..
  - python setup.py test
