language: cpp
os:
  - osx
  - linux
osx_image: xcode9.2
env:
  - PYENV_VERSION='2.7.13' PYENV_VERSION_STRING='Python 2.7.13'
  - PYENV_VERSION='3.6.4' PYENV_VERSION_STRING='Python 3.6.4'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
before_install:
  - "[ ${TRAVIS_OS_NAME} = 'linux' ] && export CXX=g++-6 || true"
  - cd /opt/pyenv/plugins/python-build/../.. && git pull && cd -
  - pyenv install ${PYENV_VERSION}
  - pyenv global ${PYENV_VERSION}
install:  
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user matplotlib
  - pip install --user sklearn
  - pip install --user scikit-build
  - pip install --user twine
  - pip install --user wheel
script:
  - python setup.py install --user
  - python setup.py test
deploy:
  provider: pypi
  user: classner
  password:
    secure: "xvUMvOco/UCiNmnXQw8A1oaAlGyUhdfOI+lxFVZ5Hgpmo2AHIHISwxhtAXu2WpvpFw+8qSxso1Xl2CxxxM4lVj3cnl/i5n04DFwz/3weJJEcQwJfR5s+hXnWHNsCszF+oVPQDXMiPkkXiHWDBih6iZJTzCubVuT/DCmg03dX4wDyQDzHALaLbhH9FLAmKlG5KYjax1vEk4Yd7AHznhRKuE/jjum/7CYGdownJ9Yqq4BquG65Os7OMBgbCJBBmH86mKlzqmuxeOD4gssxSfCVlzQHAL2woEZEB9BqJhJ/ehkBmJIPKkEl91rM92BQ/qgozp/ENJwRdx8n4p7pdOiFwYoSDjMSrFCuHQVfm3GJclVHH/MmFAjr2ePtiqTE4orE/Qjr+d4FKpdxLoLOEKm2q0razAeeS3sakkljg2PY6DYuX7cfsPsgiXiFYCVWC7uU9qqkt1L+Fj9+tEdreaqpfzMcqtWeLPaLH7IlxAmau/604Pxq8MZJGL/8th9+hpaxZnDWvmPQGDrtLSv/tjPWraKNuwmwgBK+B5xf3JPTV/HYfbKPqwAEVl9u5LVzwl2nn2JFLssRf0JWn/4OwWzr3zjisLJ5XA0lUTdF9jRrWfiJjQ/9Y3knYuGtGdt0c/Q1oCcX61yd9c3Z35lElhd2zVr6BeXwIQ/JdH5ny31b2pI="
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
