language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - kalakris-cmake
    packages:
      - g++-6
      - clang-3.8
      - cmake
      - ninja
      - python-pip
      - python-numpy
      - python-scipy
      - python-matplotlib
install:  
  - "[ $CXX = g++ ] && export CXX=g++-6 || true"
  - "[ $CXX = clang++ && export CXX=clang++-3.8 || true"
script:
  - pip install --user scikit-build
  - python setup.py install
test:
  - python setup.py test
