language: cpp
os:
  - osx
  - linux
osx_image: xcode9.2
env:
  - PYENV_VERSION='2.7.13' PYENV_VERSION_STRING='Python 2.7.13'
  - PYENV_VERSION='3.6.4' PYENV_VERSION_STRING='Python 3.6.4'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache
before_install:
  - |
      if [[ -n "$PYENV_VERSION" && "${TRAVIS_OS_NAME}" = 'osx' ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
        export PATH="${PYENV_ROOT}/bin:$PATH"
        deactivate
      fi
  - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        export CXX=g++-6
        cd /opt/pyenv && git pull origin master && cd -
        export PATH=/opt/pyenv/versions/${PYENV_VERSION}/bin:${PATH}
        pyenv install ${PYENV_VERSION}
        ls /opt/pyenv/versions/${PYENV_VERSION}/bin
      fi
  - pyenv global ${PYENV_VERSION}
install:  
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user matplotlib
  - pip install --user sklearn
  - pip install --user scikit-build
  - pip install --user twine
  - pip install --user wheel
script:
  - python setup.py install --user
  - python setup.py test
deploy:
  provider: pypi
  user: classner
  password:
    secure: "qg/bgxBxjZMR5AeJQ74zwpxLtsHCH0M4a4h0aGByi7zc1g5TXfANKpCGiXRbXN6+jnbLyRWz7Bj6SIA8EhZ5gKgwtHPxZ5cfaJqGf7r4nX0qVwob+UzoQ9jZSLHrkJbD8wS3V++DBIKpn7ErGQY+FRW4mCLrmdT1O0oiKSw7ecJkL3en/CD1XLdqkMK2V6Xyz+kRIMX3fogLUotj0x48abNZkOugkKcg5pGITHY0QdAAxkLsfl3vXcy9NDYaSJenwL0qV61bgDnANc2T6PWix3s2CkxAbznkVZP4tpsQPYyBRAR1wHQ1uG23v41SQV20LzMuzSvqkrq7tyZA272rNGPn8D3Z8tv5bexyS+ODBrO5kfwpzKrLCLQK5IfGhvcRzTfROFV8C22OI9STmM0XvfTepkWwbdHkvVTBjAQ4nwM/HV0Q+b9FKxsvENsudq1u4Spi89BBho6a1O/IyinZ1VwR6AL1fy+RS8lRYCdWEoqrJiBst9VhMc2FBF/lrdYbYyK8xNylpbfPv73gCIYa7oEnf8sdzxzaguuArvhzKlJNv7+RqKDgzo6gJCoDR1FTcTUIAso6gtnBvVDqiXQmTurcbkR/b767Lj9vxVNXCIpfLIbEd2LHfDQaDvTl/0esaOCFLZRmMyYZW8H/tNEkLhRTlZ5CZBMIAQezS984/TQ="
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
